trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: Docker@2
  displayName: 'Build docker container'  
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dil001/sonoff-server'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest